Codigo/Fast Entregas/Fast Entregas/Controllers/EntregaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Model;
using Services;

namespace FastEntregasWeb.Controllers
{
    [Authorize]
    public class EntregaController : Controller
    {
        private readonly IGerenciadorEntrega gerenciadorEntrega;
        private readonly IGerenciadorUsuario gerenciadorUsuario;
        private readonly IGerenciadorFormaPagamento gerenciadorFormaPagamento;
        private readonly IGerenciadorFormaPagamentoHasEntrega gerenciadorPagamento;

        public EntregaController(IGerenciadorEntrega _gerenciadorEntrega, IGerenciadorUsuario _gerenciadorUsuario, IGerenciadorFormaPagamento _gerenciadorFormaPagamento, IGerenciadorFormaPagamentoHasEntrega _gerenciadorPagamento)
        {
            gerenciadorEntrega = _gerenciadorEntrega;
            gerenciadorUsuario = _gerenciadorUsuario;
            gerenciadorFormaPagamento = _gerenciadorFormaPagamento;
            gerenciadorPagamento = _gerenciadorPagamento;
        }

        // GET: Entrega
        public ActionResult Index()
        {    
            string userName = User.Identity.Name;
            var usuario = gerenciadorUsuario.ObterPorUserName(userName);
            if (usuario != null)
            {                
                return View(gerenciadorEntrega.ObterTodos().Where(entrega=> entrega.CodUsuarioCliente.Equals(usuario.CodUsuario)));
            }
            return View();
        }

        public ActionResult GastoDia()
        {
            string userName = User.Identity.Name;
            var usuario = gerenciadorUsuario.ObterPorUserName(userName);
            if (usuario != null)
            {
                return View(gerenciadorEntrega.GetGastoDia(usuario.CodUsuario));
            }
            return View();
        }

        public ActionResult CorridasDia()
        {
            string userName = User.Identity.Name;
            var usuario = gerenciadorUsuario.ObterPorUserName(userName);
            if (usuario != null)
            {
                return View(gerenciadorEntrega.GetCorridasDia(usuario.CodUsuario));
            }
            return View();
        }

        // GET: Entrega/Details/5
        public ActionResult Details(int id)
        {
            Entrega entrega = gerenciadorEntrega.Obter(id);
            return View(entrega);
        }

        // GET: Entrega/Create
        public ActionResult Create()
        {
            string userName = User.Identity.Name;
            var usuario = gerenciadorUsuario.ObterPorUserName(userName);
            if (usuario != null)
            {
                ViewBag.codUsuario = usuario.CodUsuario;
                return View();
            }
            return RedirectToAction("Index", "Home");
        }

        // POST: Entrega/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EntregaModel entregaModel)
        {
            Entrega entrega = Atribuir(entregaModel);
            int codFormaPagamento = gerenciadorFormaPagamento.ObterPorDescricao(entregaModel.FormaPagamento).CodFormaPagamento;
            FormaspagamentoHasEntrega pagamento = new FormaspagamentoHasEntrega();
            pagamento.CodFormaPagamento = codFormaPagamento;
            pagamento.Valor = entrega.Valor;
            if (ModelState.IsValid)
            {
                
                int codEntrega = gerenciadorEntrega.Inserir(entrega);
                pagamento.CodEntrega = codEntrega;
                gerenciadorPagamento.Inserir(pagamento);
                return RedirectToAction(nameof(Index));
            }

            return View(entregaModel);
        }

        // GET: Entrega/Edit/5
        public ActionResult Edit(int id)
        {
            Entrega entrega = gerenciadorEntrega.Obter(id);
            return View(entrega);
        }

        // POST: Entrega/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Entrega entrega)
        {
            if (ModelState.IsValid)
            {
                gerenciadorEntrega.Editar(entrega);
                return RedirectToAction(nameof(Index));
            }

            return View(entrega);
        }

        // GET: Entrega/Delete/5
        public ActionResult Delete(int id)
        {
            Entrega entrega = gerenciadorEntrega.Obter(id);
            return View(entrega);
        }

        // POST: Entrega/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            gerenciadorEntrega.Remover(id);
            return RedirectToAction(nameof(Index));
        }

        private Entrega Atribuir(EntregaModel entrega)
        {
            Entrega e = new Entrega();
            e.CodEntrega = entrega.CodEntrega;
            e.Origem = entrega.Origem;
            e.Destino = entrega.Destino;
            e.Data = DateTime.Now;
            e.Status = "solicitada";
            e.Valor = entrega.Valor;
            e.Duracao = entrega.Duracao;
            e.Distancia = entrega.Distancia;
            e.Descricao_origem = entrega.Descricao_origem;
            e.Descricao_destino = entrega.Descricao_destino;
            e.Categoria_veiculo = entrega.Categoria_veiculo;
            e.CodUsuarioCliente = entrega.CodUsuarioCliente;
            e.CodUsuarioEntregador = entrega.CodUsuarioEntregador;
            e.CodVeiculo = entrega.CodVeiculo;

            return e;
        }
    }
}

Codigo/Fast Entregas/Fast Entregas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Fast_Entregas</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3 fixed-top" style="background-color: rgb(157,203,43)">
            <div class="container">

                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/imagens/Logo.png" alt="Logo" style="height: auto; width: 200px" class="navbar-brand img-fluid" />
                </a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="navbar-toggler-icon"> </span>
                </button>

            </div>
        </nav>
    </header>

    <div class="container" style="margin-top:90px">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Fast Entregas
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Codigo/Fast Entregas/Fast Entregas/Views/Shared/_LayoutCliente.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>@ViewData["Title"] - Fast_Entregas</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
        <script src="https://kit.fontawesome.com/a076d05399.js"></script>
        <script src="https://www.w3schools.com/lib/w3.js"></script>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="w3-sidebar w3-bar-block w3-collapse w3-card w3-animate-left w3-display-left w3-border-right w3-border-black w3-quarter" style="width: 230px;" id="mySidebar">

        <button class="w3-bar-item w3-button w3-large w3-hide-large" onclick="w3_close()">Close &times;</button>

        <a asp-area="" asp-controller="Entrega" asp-action="Create">
            <img src="~/imagens/Slogan.png" alt="Logo" class="w3-bar-item w3-border-bottom" />
        </a>

        <a href="~/Entrega/Create" class="w3-bar-item w3-button w3-border-bottom">
            <i class="fas fa-shipping-fast" style="font-size:15px; color: rgb(157,203,43); margin-right: 8px;"></i>
            Nova Entrega
        </a>

        <a href="~/Entrega/Index" class="w3-bar-item w3-button w3-border-bottom">
            <i class="fas fa-history" style="font-size:15px; color: rgb(157,203,43); margin-right: 8px;"></i>
            Minhas Entregas
        </a>

        <a href="~/Cartao/Index" class="w3-bar-item w3-button w3-border-bottom">
            <i class="fas fa-wallet" style="font-size:15px; color: rgb(157,203,43); margin-right: 8px;"></i>
            Formas de Pagamento
        </a>

        <a href="~/Identity/Account/Manage/Index" class="w3-bar-item w3-button w3-border-bottom">
            <i class="fas fa-user" style="font-size:15px; color: rgb(157,203,43); margin-right: 8px;"></i>
            Minha Conta
        </a>

        <div class="w3-display-bottommiddle" style="width:100%">
            <a href="~/SolicitacaoDeCadastro/Create" class="w3-bar-item w3-button w3-border-top" style="background-color: black;">
                <i class="fas fa-truck-loading" style="font-size:15px; color: rgb(157,203,43); margin-right: 8px;"></i>
                <h style="color:rgb(157,203,43)">Seja Entregador</h>
            </a>

            <form  asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })" >
                <button type="submit" style="background-color: transparent; border: 0px;" class="w3-bar-item w3-button w3-border-top">
                    <i class="fas fa-door-closed" style="font-size:15px; color: black; margin-right: 8px;"></i>
                    Sair
                </button>
            </form>
        </div>

    </div>

    <div class="w3-main" style="margin-left:230px;height:100%">
        <partial name="_CookieConsentPartial" />
        <div class="w3-black">
            <button class="w3-button w3-black w3-xlarge w3-hide-large" onclick="w3_open()">&#9776;</button>
        </div>
        <div class="w3-container" style="padding:0px;height:100%">
            @RenderBody()
        </div>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Codigo/Fast Entregas/Fast Entregas/Views/Shared/_LayoutEntregador.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>@ViewData["Title"] - Fast_Entregas</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
        <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="margin: 0%; padding: 0%;">
    <div class="w3-sidebar w3-bar-block w3-collapse w3-card w3-animate-left w3-display-left w3-border-right w3-border-black w3-quarter" style="width: 230px;" id="mySidebar">

        <button class="w3-bar-item w3-button w3-large w3-hide-large" onclick="w3_close()">Close &times;</button>

        <a asp-area="" asp-controller="Home" asp-action="Index">
            <img src="~/Images/Cores.png" alt="Logo" class="w3-bar-item w3-border-bottom" />
        </a>

        <a href="#" class="w3-bar-item w3-button w3-border-bottom">
            <i class="fas fa-route" style="font-size:15px; color: rgb(157,203,43); margin-right: 8px;"></i>
            Solicitações de Entrega
        </a>

        <a href="#" class="w3-bar-item w3-button w3-border-bottom">
            <i class="fas fa-piggy-bank" style="font-size:15px; color: rgb(157,203,43); margin-right: 8px;"></i>
            Conta Bancária
        </a>

        <a href="#" class="w3-bar-item w3-button w3-border-bottom">
            <i class="fas fa-fighter-jet" style="font-size:15px; color: rgb(157,203,43); margin-right: 8px;"></i>
            Veículos
        </a>

        <a href="#" class="w3-bar-item w3-button w3-border-bottom">
            <i class="fas fa-shipping-fast" style="font-size:15px; color: rgb(157,203,43); margin-right: 8px;"></i>
            Novo Pedido
        </a>

        <a href="#" class="w3-bar-item w3-button w3-border-bottom">
            <i class="fas fa-wallet" style="font-size:15px; color: rgb(157,203,43); margin-right: 8px;"></i>
            Formas de Pagamento
        </a>

        <a href="#" class="w3-bar-item w3-button w3-border-bottom">
            <i class="fas fa-history" style="font-size:15px; color: rgb(157,203,43); margin-right: 8px;"></i>
            Histórico
        </a>

        <a href="#" class="w3-bar-item w3-button w3-border-bottom">
            <i class="fas fa-user" style="font-size:15px; color: rgb(157,203,43); margin-right: 8px;"></i>
            Minha Conta
        </a>

        <a href="#" class="w3-bar-item w3-button w3-border-top w3-display-bottommiddle">
            <i class="fas fa-door-closed" style="font-size:15px; color: black; margin-right: 8px;"></i>
            Sair
        </a>

    </div>

    <div class="w3-main container-fluid" style="margin-left:230px; height:100%">
        <partial name="_CookieConsentPartial" />
        <div>
            <button class="w3-button w3-black w3-xlarge w3-hide-large" onclick="w3_open()">&#9776;</button>
        </div>
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Codigo/Fast Entregas/Fast Entregas/Views/Shared/_LayoutHome.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Fast_Entregas</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="home">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3 fixed-top" style="background-color: rgb(157,203,43)">
            <div class="container">

                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/imagens/Logo.png" alt="Logo" style="height: auto; width: 200px" class="navbar-brand img-fluid" />
                </a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="navbar-toggler-icon"> </span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="container" style="margin-top:90px">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Fast Entregas
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>